chore(TDB): Setup of Error Handlers and Serialization
mohammed-sharraf-sazim/The-Todo-BE pull request #3
Opened 2024-08-06 11:14 UTC by mohammed-sharraf-sazim

###Description of Change:
- Added Error handlers and serializers in the server side. 
###Associated Ticket Link(s):
- https://trello.com/c/vMm9SJwS/18-error-handlers-and-serializers

### Developers Note:
- Made some minor change in the TaskPriority enum of the entity.

2024-08-07 10:45 UTC, mahir-mohsin-sazim requested changes

2024-08-07 10:45 UTC, mahir-mohsin-sazim commented on src/main.ts
> +  // Enable CORS
remove comments

2024-08-07 10:49 UTC, nur-zaman-sazim requested changes

2024-08-07 10:49 UTC, nur-zaman-sazim commented on src/main.ts
> +    origin: 'http://localhost:3001', // Your frontend URL
- read origin from .env
- remove comments

2024-08-07 18:34 UTC, mohammed-sharraf-sazim commented on src/main.ts
> +  // Enable CORS
Comments Removed

2024-08-07 18:34 UTC, mohammed-sharraf-sazim commented on src/main.ts
> +    origin: 'http://localhost:3001', // Your frontend URL
Did what you instructed

2024-08-07 19:13 UTC, nur-zaman-sazim approved these changes

2024-08-08 06:39 UTC, mahir-mohsin-sazim approved these changes

2024-08-08 06:46 UTC, merged